name: React App Docker Image Build and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubantu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: Use Node.js 18
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm ci

    - name: 🔨 Build Project
      run: npm run build --production

    - name: Build Dcoker Image
      run: docker build . --tag docker-demo:$(date +%s)
